@startuml
package "Танковые бои" {
 [Сервис аутентификации]
 [Сервис управления турнирами]
 [Сервис управления боями]
 [Сервис уведомлений]
 [Сервис рейтинга]
}

node "Веб-приложение для участников" {
}

node "Веб-приложение для организаторов" {
}

node "Приложение 'Агент'" {
}

[Сервис аутентификации] <--> [Сервис управления турнирами] : HTTP
[Сервис управления турнирами] --> [Сервис управления боями] : HTTP
[Сервис управления боями] --> [Сервис уведомлений] : AMQP
[Сервис уведомлений] --> [Сервис рейтинга] : HTTP

[Сервис аутентификации] <-- [Веб-приложение для участников] : HTTP
[Сервис аутентификации] <-- [Веб-приложение для организаторов] : HTTP
[Сервис аутентификации] <-- [Приложение 'Агент'] : HTTP

[Сервис управления турнирами] <-- [Веб-приложение для организаторов] : HTTP

[Сервис управления боями] <-- [Веб-приложение для участников] : HTTP
[Сервис управления боями] <-- [Приложение 'Агент'] : HTTP

[Сервис уведомлений] <-- [Веб-приложение для участников] : HTTP
[Сервис уведомлений] <-- [Веб-приложение для организаторов] : HTTP

[Сервис рейтинга] <-- [Веб-приложение для участников] : HTTP
[Сервис рейтинга] <-- [Веб-приложение для организаторов] : HTTP
@enduml
